language: python
matrix:
  include:
  # generic checks
  - python: "3.9"
    env: TOX_ENV=flake8
  - python: "3.9"
    env: TOX_ENV=check_rst
  - python: "3.9"
    env: TOX_ENV=coverage
  # Django additional supported version
  - python: "3.9"
    env: TOX_ENV=py39-django40
  - python: "3.9"
    env: TOX_ENV=py39-django40

cache:
  directories:
    - $HOME/.cache/pip/http/
    - $HOME/build/KenWhitesell/django-4-cas-server/.tox/$TOX_ENV/
install:
  - travis_retry pip install setuptools --upgrade
  - pip install tox $PKGS
  - pip freeze
script:
  - tox -e $TOX_ENV
after_script:
  - cat tox_log/*.log
